package:
  name: gitlab-kas
  version: 17.0.0
  epoch: 0
  description: GitLab Kas is a component installed together with GitLab. It is required to manage the GitLab agent for Kubernetes.
  copyright:
    - license: MIT

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: fetch
    with:
      # https://gitlab.com/gitlab-org/build/CNG/-/tree/master/gitlab-kas
      uri: https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent/-/archive/v${{package.version}}/gitlab-agent-v${{package.version}}.tar.gz
      expected-sha256: e9d54880f24a4326fa53a5b2843b457dd8ed1788a625119509a84b90a2a04cac

  - uses: go/bump
    with:
      deps: k8s.io/apimachinery@v0.30.0

  - uses: go/build
    with:
      packages: ./cmd/kas
      output: kas
      ldflags: "-w -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd.Version=v${{package.version}} -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd.Commit=v${{package.version}} -X gitlab.com/gitlab-org/cluster-integration/gitlab-agent/v16/cmd.BuildTime=$(date +%F-%T)"

  - uses: strip

update:
  enabled: true
  release-monitor:
    identifier: 369632
