package:
  name: wolfictl
  version: 0.16.10
  epoch: 0
  description: Helper CLI for managing Wolfi
  copyright:
    - license: Apache-2.0

environment:
  environment:
    CGO_ENABLED: "0"

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/wolfi-dev/wolfictl
      tag: v${{package.version}}
      expected-commit: f4a8745f81cbf13566faa3f43dff651007448205
      destination: wolfictl

  - uses: go/bump
    with:
      deps: github.com/opencontainers/runc@v1.2.0-rc.1
      replaces: github.com/mholt/archiver/v3=github.com/anchore/archiver/v3@v3.5.2
      modroot: wolfictl

  - uses: go/build
    with:
      packages: .
      output: wolfictl
      modroot: wolfictl

  - uses: strip

update:
  enabled: true
  github:
    identifier: wolfi-dev/wolfictl
    strip-prefix: v
    use-tag: true
